import {
  loadTasksFromStorage,
  saveTasksToStorage,
} from "../utils/localStorage.js";
import { clearExistingTasks, renderTasks } from "../ui/render.js";
import { resetForm } from "./formUtils.js";

/**
 * Creates a new task using the values from the "Add New Task" form,
 * saves it to localStorage, re-renders the board, resets the form,
 * and closes the modal overlay.
 *
 * - Title is required (if it's empty, nothing happens)
 * - A new ID is generated by taking the highest existing ID + 1
 *
 * @returns {void}
 */
export function addNewTask() {
  const title = document.getElementById("title-input").value.trim();
  const description = document.getElementById("desc-input").value.trim();
  const status = document.getElementById("select-status").value;
  const overlay = document.querySelector(".modal-overlay");
  const priority = document.getElementById("select-priority").value;

  if (!title) return;

  const tasks = loadTasksFromStorage();
  const newTask = {
    id: tasks.length ? Math.max(...tasks.map((t) => t.id)) + 1 : 1,
    title,
    description,
    status,
    priority,
  };

  const updatedTasks = [...tasks, newTask];
  saveTasksToStorage(updatedTasks);

  clearExistingTasks();
  renderTasks(updatedTasks);
  resetForm();
  overlay.close();
}

/**
 * Updates an existing task by its ID.
 *
 * It:
 * - loads all tasks from localStorage
 * - finds the task with the matching ID
 * - updates it using the values in `updatedData`
 * - saves the new task list back to localStorage
 * - re-renders the board
 *
 * @param {number} taskId - The ID of the task you want to update.
 * @param {Object} updatedData - The fields you want to change (example: { title, status, priority }).
 * @returns {void}
 */
export function editTask(taskId, updatedData) {
  const tasks = loadTasksFromStorage();
  const updatedTasks = tasks.map((task) =>
    task.id === taskId ? { ...task, ...updatedData } : task
  );
  saveTasksToStorage(updatedTasks);

  clearExistingTasks();
  renderTasks(updatedTasks);
}


/**
 * Deletes a task by its ID.
 *
 * It:
 * - loads all tasks from localStorage
 * - removes the task with the matching ID
 * - saves the updated list
 * - re-renders the board
 *
 * @param {number} taskId - The ID of the task you want to delete.
 * @returns {void}
 */
export function deleteTask(taskId) {
  const tasks = loadTasksFromStorage();
  const updatedTasks = tasks.filter((task) => task.id !== taskId);
  saveTasksToStorage(updatedTasks);

  clearExistingTasks();
  renderTasks(updatedTasks);
}



